### ISSUE TITLE
YBP Brill Import Profile

### ISSUE THREAD

**Issue by pdiskin** [pulibrary/alma-notices#211]
The YBP Brill Retention plan is active.  We got our first record.  I made an import profile in the sandbox:
 YBP Brill Print Approval
I reused the same delete 984 used for CAS Y plan.  The holdings note was added.  And the same problem exists with the item retention.
The one thing I'm not complete sure I did correctly and perhaps the vendor needs to make an adjustment as well is with the Holdings Mapping.
Sample CAS Y 
=984  1\$acommitted to retain$din perpetuity$fReCAP$2Italian Language Imprints Collaborative Collection$5NjP$uhttp://arks.princeton.edu/ark:/88435/dcxg94j1575
Cas Y mapping: 
984 a,d,f,2,5,u. becomes 583 a,d,ff,5,u

Sample YBP BRill:
=984  1\$acommitted to retain$c20230101$dindefinite until ended by the majority of agreeing parties$fIvy Plus Libraries Confederation Shared Book Collection - Book Plan for Brill Monographs$xCoded under interim guidelines$5NjP
YBP Mapping:
984 a,c,d,f,x,5

**Comment by pdiskin** [comment]
When we enter this into production we need to add a fund mapping for 00AN572mon for general approval plan

**Comment by pmgreen** [comment]
Intended for alma-config
